docker-compose-yaml: docker-compose.yml
environments:
  main:
    routes:
      - nginx:
        - demo.lagoon.weystrom.net:
            tls-acme: 'true'
            insecure: Redirect
routes:
  autogenerate:
    enabled: false
