version: '2.3'

x-lagoon-project:
  &lagoon-project "pbasov-lagoon-example"

x-environment:
  &default-environment
    LAGOON_PROJECT: *lagoon-project

x-user:
  &default-user
    # The default user under which the containers should run. Change this if you are on linux and run with another user than ID `1000`
    user: '1000'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    labels:
      lagoon.type: nginx 

